### ISSUE TITLE
Can't install dependencies if `pod setup` has not been run

### ISSUE THREAD

**Issue by petercv** [jcampbell05/cocoapods-deploy#3]
So I'm trying to integrate cocoapods-deploy in our CI environment. The CI environment runs in a blank slate OS X VM which does not have any pod specs because `pod setup` has never been run.

Initially the installing of the pods looks fine, but than I run into the error below. Maybe we should simply make sure the VM has an old spec repository even though it might not be used. But for CI environments it would be really helpful to not have the need to have the spec repository checked out locally.

```
- Deploying Pods
- Deploying google-cast-sdk 2.10.1
Fetching podspec for `google-cast-sdk` from `https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/google-cast-sdk/2.10.1/google-cast-sdk.podspec.json`
- Deploying google-cast-sdk/Assets 2.10.1
Fetching podspec for `google-cast-sdk` from `https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/google-cast-sdk/2.10.1/google-cast-sdk.podspec.json`
- Deploying google-cast-sdk/Core 2.10.1
Fetching podspec for `google-cast-sdk` from `https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/google-cast-sdk/2.10.1/google-cast-sdk.podspec.json`
- Deploying Google-Mobile-Ads-SDK 7.1.0
Fetching podspec for `Google-Mobile-Ads-SDK` from `https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/Google-Mobile-Ads-SDK/7.1.0/Google-Mobile-Ads-SDK.podspec.json`
- Deploying GoogleAds-IMA-iOS-SDK-For-AdMob 3.0.beta.16
Fetching podspec for `GoogleAds-IMA-iOS-SDK-For-AdMob` from `https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/GoogleAds-IMA-iOS-SDK-For-AdMob/3.0.beta.16/GoogleAds-IMA-iOS-SDK-For-AdMob.podspec.json`
- Deploying GoogleAnalytics-iOS-SDK 3.10
Fetching podspec for `GoogleAnalytics-iOS-SDK` from `https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/GoogleAnalytics-iOS-SDK/3.10/GoogleAnalytics-iOS-SDK.podspec.json`
- Deploying GoogleAnalytics-iOS-SDK/Core 3.10
Fetching podspec for `GoogleAnalytics-iOS-SDK` from `https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/GoogleAnalytics-iOS-SDK/3.10/GoogleAnalytics-iOS-SDK.podspec.json`
Analyzing dependencies
GoogleAnalytics-iOS-SDK/Core (= 3.10)
Google-Mobile-Ads-SDK (~> 7.0)
google-cast-sdk/Core (= 2.10.1)
google-cast-sdk/Assets (= 2.10.1)
google-cast-sdk/Core
GoogleAnalytics-iOS-SDK/Core (= 3.10)
Google-Mobile-Ads-SDK (~> 7.0)
google-cast-sdk/Core (= 2.10.1)
google-cast-sdk/Assets (= 2.10.1)
google-cast-sdk/Core (= 2.10.1)
google-cast-sdk/Assets (= 2.10.1)
google-cast-sdk/Core
Downloading dependencies
Installing Google-Mobile-Ads-SDK (7.1.0)
Installing GoogleAds-IMA-iOS-SDK-For-AdMob (3.0.beta.16)
Installing GoogleAnalytics-iOS-SDK (3.10)
Installing google-cast-sdk (2.10.1)
Generating Pods project
Integrating client project
```
### Command

```
/usr/local/bin/pod deploy
```
### Report
- What did you do?
- What did you expect to happen?
- What happened instead?
### Stack

```
CocoaPods : 0.39.0
Ruby : ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]
RubyGems : 2.0.14
Host : Mac OS X 10.11.3 (15D21)
Xcode : 7.2.1 (7C1002)
Git : git version 2.5.4 (Apple Git-61)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories :
```
### Plugins

```
cocoapods-deploy : 0.0.2
cocoapods-plugins : 0.4.2
cocoapods-search : 0.1.0
cocoapods-stats : 0.6.2
cocoapods-trunk : 0.6.4
cocoapods-try : 0.5.1
```
### Podfile

``` ruby
source 'https://github.com/CocoaPods/Specs.git'
xcodeproj 'Project/Project.xcodeproj'
platform :ios, '6.0'
pod 'Google-Mobile-Ads-SDK', '~> 7.1'
pod 'GoogleAnalytics-iOS-SDK', '~> 3.0'

# To make sure ads play in the background. see: https://developers.google.com/interactive-media-ads/docs/sdks/ios/background_ad_playback
pod 'GoogleAds-IMA-iOS-SDK-For-AdMob', '~> 3.0.beta.13'

pod 'google-cast-sdk', '~> 2.10.1'
```
### Error

```
Errno::ENOENT - No such file or directory - /Users/user/.cocoapods/repos/master
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/source.rb:41:in `chdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/source.rb:41:in `url'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-0.6.2/lib/cocoapods_plugin.rb:4:in `validates?'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-0.6.2/lib/cocoapods_plugin.rb:25:in `block in <module:CocoaPodsStats>'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:117:in `call'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:117:in `block (3 levels) in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:140:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:111:in `block (2 levels) in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:109:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:109:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:140:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:108:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:481:in `run_plugins_post_install_hooks'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:462:in `perform_post_install_actions'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:113:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-deploy-0.0.2/lib/cocoapods-deploy/command/deploy.rb:160:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-deploy-0.0.2/lib/cocoapods-deploy/command/deploy.rb:148:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by jcampbell05** [comment]
I'll have a look into this.

We use this in our Travis CI so it uses a clean VM each run, so the idea with this plugin is you shouldn't need that repository at all, only a `Podfile` and a `Podfile.lock`.

**Comment by jcampbell05** [comment]
@petercv  Do you have a copy of your `Podfile.lock` to hand ?

**Comment by petercv** [comment]
```
PODS:
  - google-cast-sdk (2.10.1):
    - google-cast-sdk/Assets (= 2.10.1)
    - google-cast-sdk/Core (= 2.10.1)
  - google-cast-sdk/Assets (2.10.1):
    - google-cast-sdk/Core
  - google-cast-sdk/Core (2.10.1)
  - Google-Mobile-Ads-SDK (7.1.0)
  - GoogleAds-IMA-iOS-SDK-For-AdMob (3.0.beta.16):
    - Google-Mobile-Ads-SDK (~> 7.0)
  - GoogleAnalytics-iOS-SDK (3.10):
    - GoogleAnalytics-iOS-SDK/Core (= 3.10)
  - GoogleAnalytics-iOS-SDK/Core (3.10)

DEPENDENCIES:
  - google-cast-sdk (~> 2.10.1)
  - Google-Mobile-Ads-SDK (~> 7.1)
  - GoogleAds-IMA-iOS-SDK-For-AdMob (~> 3.0.beta.13)
  - GoogleAnalytics-iOS-SDK (~> 3.0)

SPEC CHECKSUMS:
  google-cast-sdk: 98bafadd4c490c776f2ee913a6561cda5b8634a6
  Google-Mobile-Ads-SDK: 9b7c22345f13de4164e9e6d90ad49cce42124c3c
  GoogleAds-IMA-iOS-SDK-For-AdMob: 09274f35924ba3c4089e079430956142f66254b3
  GoogleAnalytics-iOS-SDK: 4f98a376c1d61e6ac4ca47951655820314856eef

COCOAPODS: 0.39.0
```

**Comment by jcampbell05** [comment]
@petercv On further analysis this looks like a bug triggered by `cocoapods-stats` I will look into what that plugin needs and see if I can fix it.

**Comment by petercv** [comment]
Thanks!

**Comment by jcampbell05** [comment]
For now you can disable the stats by setting the `COCOAPODS_DISABLE_STATS` enviroment to `1`

**Comment by petercv** [comment]
Nice!

**Comment by jcampbell05** [comment]
@petercv okay so I've pushed up `0.0.3` this will make sure cocoapods-stats doesn't run on the CI. I'll file an issue as that plugin should handle the situation where there is no-repo better.

Let me know how this works out for you.

**Comment by petercv** [comment]
Cool, already tried it with the environment variable you mentioned. And that seems to work fine. But I will remove it and upgrade to 0.0.3.

**Comment by jcampbell05** [comment]
@petercv okay :) I've filed this with the CocoaPods team in the meantime. Let me know your results, really looking forward to them!

**Comment by jcampbell05** [comment]
According to @segiddins this should be fixed in beta 5 of 1.0.0. I will close for now.

**Comment by petercv** [comment]
I can confirm that 0.0.4 works without the environment variable.

**Comment by jcampbell05** [comment]
Great!
